version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "sourse_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "1234"
    ports:
     - "5432:5432"