version: '3.1'

services:
  source_postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: "source_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "1234"
    ports:
     - "5432:5432"
  fill:
    build:
      context: .
    depends_on:
      - "source_postgres"
