--csv
source_type: csv
load_type: overwrite, append,
file_path: /skdjcjsd/sdckk.csv
target_table: name
fields:
    column1_name: column_type
    column2_name: column_type
    ...
key_column: id

--db
source_type: postgresql
load_type: overwrite, append,
source_table: stroka_db
target_table:
fields:
    column1_name: column_type
    column2_name: column_type
key_column: id
