version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: "sourse_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "1234"
    ports:
     - "4321:5432"
  fill:
    build:
      context: .
    depends_on:
      - "postgres"
