version: '3.1'

services:
  meta_postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: "meta_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "1234"
    ports:
     - "5433:5432"
  create:
    build:
      context: .
    depends_on:
      - "meta_postgres"
